// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMI_n64WiaM94rRxAV10uS2VmSLpzmlZY',
    appId: '1:226348593669:web:b64785df7a91773a5ba26c',
    messagingSenderId: '226348593669',
    projectId: 'sutt-f4504',
    authDomain: 'sutt-f4504.firebaseapp.com',
    storageBucket: 'sutt-f4504.appspot.com',
    measurementId: 'G-6Z8DPMSDGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCbMq_bZXufcmJOJCNUjLSZ6sdAX4pw9o',
    appId: '1:226348593669:android:0cdf0d424437d5035ba26c',
    messagingSenderId: '226348593669',
    projectId: 'sutt-f4504',
    storageBucket: 'sutt-f4504.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEzG6ir2J2fw5C0m3gMnvxVyHSspYPNOs',
    appId: '1:226348593669:ios:5a07ccd164a1826d5ba26c',
    messagingSenderId: '226348593669',
    projectId: 'sutt-f4504',
    storageBucket: 'sutt-f4504.appspot.com',
    iosBundleId: 'com.junianto.sutt',
  );
}
